# A specification to declare needed OAuth credentials (tokens, clients) for the
# Zalando Platform IAM system
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: platformcredentialssets.zalando.org
spec:
  scope: Namespaced
  group: zalando.org
  version: v1
  names:
    kind: PlatformCredentialsSet
    plural: platformcredentialssets
    singular: platformcredentialsset
    shortNames:
    - pcs
